
pins:
  - pin: A1
    id: TLE9104_1_OUT_1
    function: Injector 1 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ1
    color: orange

  - pin: A2
    id: TLE9104_1_OUT_0
    function: Injector 7 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ7
    color: blue

  - pin: A3
    class: analog_inputs
    id: EFI_ADC_15
    function: Analog 1
    ts_name: ___ - AIN1
    color: white

  - pin: A4
    id: EFI_ADC_7
    class: analog_inputs
    function: Analog 4
    ts_name: ___ - AIN4
    color: white

  - pin: B1
    id: TLE9104_1_OUT_2
    function: Injector 2 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ2
    color: orange

  - pin: B2
    id: TLE9104_1_OUT_3
    function: Injector 8 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ8
    color: orange

  - pin: B3
    id: EFI_ADC_6
    class: analog_inputs
    function: Analog 2
    ts_name: ___ - AIN2
    color: white

  - pin: B4
    id: EFI_ADC_14
    class: analog_inputs
    function: Analog 5
    ts_name: ___ - AIN5
    color: white

  - pin: C1
    id: TLE9104_0_OUT_1
    function: Injector 3 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ3
    color: orange

  - pin: C2
    id: C10
    function: GPIO1
    class: outputs
    type: ls
    ts_name: ___ - GPIO1
    color: orange

  - pin: C3
    id: EFI_ADC_8
    class: analog_inputs
    function: Analog 3
    ts_name: ___ - AIN3/TIN1
    color: white

  - pin: C4
    id: EFI_ADC_9
    class: analog_inputs
    function: Analog 6
    ts_name: ___ - AIN6/TIN2
    color: white

  - pin: D1
    id: TLE9104_0_OUT_0
    function: Injector 4 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ4
    color: orange

  - pin: D2
    id: A15
    function: GPIO2
    class: outputs
    type: ls
    ts_name: ___ - GPIO2
    color: orange

  - pin: D3
    id: [E12, E12]
    class: [event_inputs, switch_inputs]
    function: Digital 1
    ts_name: ___ - DIN1
    color: white

  - pin: D4
    id: [E13, E13]
    class: [event_inputs, switch_inputs]
    function: Digital 2
    ts_name: ___ - DIN2
    color: white

  - pin: E1
    id: TLE9104_0_OUT_3
    function: Injector 5 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ5
    color: orange

  - pin: E2
    function: Can 1 high
    type: can
    color: orange

  - pin: E3
    function: Can 2 high
    type: can
    color: orange

  - pin: E4
    function: Sensor Ground
    type: gnd
    color: orange

  - pin: F1
    id: TLE9104_0_OUT_2
    function: Injector 6 Output
    class: outputs
    type: ls
    ts_name: ___ - INJ6
    color: orange

  - pin: F2
    function: Can 1 low
    type: can
    color: orange

  - pin: F3
    function: Can 2 low
    type: can
    color: orange

  - pin: F4
    function: 5VP
    type: +5V
    color: orange

  - pin: G1
    function: 12V
    type: 12V
    color: orange

  - pin: G2
    function: Ground
    type: GND
    color: orange

  - pin: G3
    function: Halfbridge driver +
    type: Output
    color: orange

  - pin: G4
    function: Halfbridge driver -
    type: Output
    color: orange

  - pin: H1
    function: 12V
    type: 12V
    color: orange

  - pin: H2
    function: Ground
    type: GND
    color: orange

  - pin: H3
    function: Halfbridge driver +
    type: Output
    color: orange

  - pin: H4
    function: Halfbridge driver -
    type: Output
    color: orange
    
  - pin: HBPFB
    id: EFI_ADC_1
    class: analog_inputs
    function: HB + feedback
    ts_name: ___
    color: white

  - pin: HBNFB
    id: EFI_ADC_2
    class: analog_inputs
    function: HB - Feedback
    ts_name: ___
    color: white

info:
  cid: main
  title: VTEGPC
  name: EGPC
  board_url: https://rusefi.com/s/vtegpc
  directory: hellen/vtegpc
  image:
    file: 34pins-3k.jpg
  pins:
