

# Target ECU board design
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp
DDEFS += -DEFI_MAIN_RELAY_CONTROL=TRUE

DDEFS += -DFIRMWARE_ID=\"VTEGPC\"

# This board has two tle9104
DDEFS += -DBOARD_TLE9104_COUNT=2


include $(BOARDS_DIR)/hellen/hellen-common100.mk


DDEFS += -DBOOT_BACKDOOR_ENTRY_TIMEOUT_MS=0

DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::E1 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::E0
DDEFS += -DTS_PRIMARY_UxART_PORT=SD8 -DEFI_TS_PRIMARY_IS_SERIAL=TRUE -DSTM32_SERIAL_USE_USART8=TRUE -DSTM32_UART_USE_USART8=FALSE

DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_VTEGPC
