meta: config/boards/hellen_meta.h

pins:
  - pin: K1
    function: GND
    type: gnd

  - pin: K2
    meta: H144_IN_VBATT
    class: analog_inputs
    ts_name: K2 Ignition Key Voltage
    function: V ign

  - pin: K3
    function: GND
    type: gnd

  - pin: K4
    function: +12v from main relay

  - pin: K5
    function: GND
    type: gnd

  - pin: K6
    function: 12v perm

  - pin: K10
    function: K10 presure sensor
    meta: H144_IN_MAP2
    class: analog_inputs
    ts_name: K10 Sensor

  - pin: K11
    function: Analog Ground

  - pin: K12
    ts_name: KNOCK - k12
    function: Knock sens. in

  - pin: K13
    function: Analog Ground

  - pin: K14
    function: Analog Ground

  - pin: K15
    meta: H144_IN_D_3
    function: 'Exhaust Cam Sensor (2014: yellow)'
    class: event_inputs
    ts_name: Exhaust Cam - K15

  - pin: K16
    function: Analog Ground


  - pin: K17b
    function: Crank Sensor
    meta: H144_IN_CRANK
    class: event_inputs
    ts_name: Crank - K17

  - pin: K18
    function: BK2 WBO IP
  - pin: K19
    function: BK2 WBO N
  - pin: K20
    function: BK2 WBO G


  - pin: K21
    meta: H144_IN_O2S
    class: analog_inputs
    ts_name: K21 Ambient Temperature
    function: Ambient Temperature

  - pin: K22
    ts_name: BK2 Wastegate Position - 22

  - pin: K25
    id: MC33810_0_OUT_0
    class: outputs
    ts_name: INJ_1 k25
    function: Injector 1
    type: inj

  - pin: K26
    id: MC33810_0_OUT_1
    class: outputs
    ts_name: INJ_2 k26
    function: Injector 2
    type: inj

  - pin: K27
    id: MC33810_0_OUT_2
    class: outputs
    ts_name: INJ_3 k27
    function: Injector 3
    type: inj

  - pin: K28
    id: MC33810_0_OUT_3
    class: outputs
    ts_name: INJ_4 k28
    function: Injector 4
    type: inj

  - pin: K30
    function: sensor +5v feed
    type: 5v

  - pin: K31
    meta: H144_IN_MAP1
    class: analog_inputs
    ts_name: Map Sensor ___
    function: Manifold Pressure Sensor

  - pin: K32
    meta: H144_IN_AUX1
    class: analog_inputs
    ts_name: TPS 2
    function: TPS 2 sensor input

  - pin: K33
    meta: H144_IN_CLT
    class: analog_inputs
    ts_name: CLT
    function: CLT

  - pin: K34
    function: Analog Ground

  - pin: K35
    meta: H144_IN_AUX2
    class: analog_inputs
    ts_name: PPS 2
    function: PPS 2 sensor input

  - pin: K36
    function: sensor +5v feed
    type: 5v

  - pin: K37
    function: Analog Ground

  - pin: K39
    function: Analog Ground

  - pin: K40
    meta: H144_IN_VSS
    class: event_inputs
    ts_name: K40 VSS
    function: Vehicle Speed Sensor

  - pin: K42
    function: BK2 WBO RC

  - pin: K43
    function: sensor +5v feed
    type: 5v

  - pin: K44
    function: Analog Ground

  - pin: K47
    meta: H144_LS_7
    class: outputs
    ts_name: ___ BK1 Wastegate Solenoid
    function: BK1 Wastegate Solenoid

  - pin: K53
    meta: H144_IN_IAT
    class: analog_inputs
    ts_name: IAT
    function: 'IAT (2014: green)'

  - pin: K54
    meta: H144_IN_MAP3
    class: analog_inputs
    ts_name: ___ A/C pressure
    function: A/C pressure

  - pin: K57
    function: 'Analog Ground (2014: green)'

  - pin: K58
    meta: H144_IN_O2S2
    class: analog_inputs
    ts_name: ___ Oil Temp
    function: 'Oil Temperature (2014: blue/orange)'

  - pin: K59
    function: 'Analog Ground (2014: black)'

  - pin: K60
    function: 'sensor +5v feed (2014: grey)'
    type: 5v

  - pin: K61
    function: 'Analog Ground (2014: yellow)'

  - pin: K62
    meta: H144_IN_D_2
    function: Intake Cam Sensor
    class: event_inputs
    ts_name: Intake Cam - ___

  - pin: K63
    function: sensor +5v feed
    type: 5v

  - pin: K64
    meta: H144_OUT_IO3
    class: outputs
    ts_name: Main Relay ___
    function: Main relay control
    type: ls

  - pin: K65
    meta: H144_OUT_IO7
    class: outputs
    ts_name: Fan Relay Low
    function: Fan relay low

  - pin: K66
    meta: H144_LS_5
    class: outputs
    ts_name: VVT1
    function: VVT1

  - pin: K68
    meta: H144_LS_6
    class: outputs
    ts_name: VVT2
    function: VVT2


  - pin: K70
    meta: H144_OUT_IO9
    class: outputs
    ts_name: Fuel Pump ___
    function: Fuel Pump Relay
    type: ls

  - pin: K71
    ts_name: ETB w1
    function: DC Motor w1

  - pin: K72
    ts_name: ETB w2
    function: DC Motor w2

  - pin: K77
    function: CAN bus high
    type: can

  - pin: K78
    function: CAN bus low
    type: can

  - pin: K79
    function: Analog Ground

  - pin: K80
    meta: H144_IN_TPS
    class: analog_inputs
    ts_name: TPS 1
    function: TPS 1 sensor input

  - pin: K82
    meta: H144_IN_PPS
    class: analog_inputs
    ts_name: PPS 1
    function: PPS 1 sensor input

  - pin: K85
    function: Analog Ground

  - pin: K86
    meta: H144_OUT_PWM7
    class: outputs
    ts_name: Tacho
    function: Tachometer

  - pin: K87
    meta: H144_OUT_IO10
    class: outputs
    ts_name: K87 AC Relay
    function: A/C Relay
    type: ls

  - pin: K88
    meta: H144_OUT_IO8
    class: outputs
    ts_name: Fan Relay HI
    function: Fan relay high

  - pin: K92
    meta: H144_OUT_PWM8
    class: outputs
    type: ls
    ts_name: MIL
    function: Check Engine Light

  - pin: K93
    function: BK2 WBO Heater

  - pin: A1
    id: MC33810_0_GD_3
    class: outputs
    ts_name: Coil 4
    function: Coil 4
    type: ign

  - pin: A2
    function: Shield Ground

  - pin: A15
    function: Ground

  - pin: A16
    id: MC33810_0_GD_1
    class: outputs
    ts_name: Coil 2
    function: Coil 2
    type: ign

  - pin: A29
    meta: H144_IN_RES3
    class: switch_inputs
    ts_name: A29 Brake Input
    function: Brake Switch


  - pin: A31
    id: MC33810_0_GD_0
    class: outputs
    ts_name: Coil 1
    function: Coil 1
    type: ign

  - pin: A43
    meta: H144_IN_RES2
    class: switch_inputs
    ts_name: A43 Clutch Input
    function: Clutch Input

  - pin: A45
    function: BK2 DC Wastegate Pos

  - pin: A46
    id: MC33810_0_GD_2
    class: outputs
    ts_name: Coil 3
    function: Coil 3
    type: ign

  - pin: A57
    meta: H144_IN_RES1
    class: switch_inputs
    ts_name: A57 AC Request
    function: AC Request Switch

  - pin: A60
    function: BK2 DC Wastegate Neg

info:
  board_url: https://github.com/rusefi/rusefi/wiki/Hellen-154-Hyundai
  directory: hellen/hellen154hyundai_revD
  title: Hellen 154 Hyundai
  order: 0
  image:
    file: main.jpg
  pins:
    - pin: K1
      x: 1900
      y: 660
    - pin: K2
      x: 2055
      y: 660

    - pin: K3
      x: 1900
      y: 458
    - pin: K4
      x: 2055
      y: 458

    - pin: K5
      x: 1900
      y: 259
    - pin: K6
      x: 2055
      y: 259

    - pin: K7
      x: 2251
      y: 660
    - pin: K8
      x: 2340
      y: 660
    - pin: K9
      x: 2412
      y: 660
    - pin: K10
      x: 2492
      y: 660
    - pin: K11
      x: 2566
      y: 660
    - pin: K12
      x: 2633
      y: 660
    - pin: K13
      x: 2714
      y: 660
    - pin: K14
      x: 2791
      y: 660
    - pin: K15
      x: 2865
      y: 660
    - pin: K16
      x: 2940
      y: 660
    - pin: K17c
      x: 3011
      y: 660
    - pin: K18
      x: 3086
      y: 660
    - pin: K19
      x: 3161
      y: 660
    - pin: K20
      x: 3235
      y: 660
    - pin: K21
      x: 3314
      y: 660
    - pin: K22
      x: 3386
      y: 660
    - pin: K23
      x: 3458
      y: 660
    - pin: K24
      x: 3530
      y: 660
    - pin: K25
      x: 3605
      y: 660
    - pin: K26
      x: 3681
      y: 660
    - pin: K27
      x: 3754
      y: 660
    - pin: K28
      x: 3827
      y: 660




    - pin: K29
      x: 2251
      y: 571
    - pin: K30
      x: 2340
      y: 571
    - pin: K31
      x: 2412
      y: 571
    - pin: K32
      x: 2492
      y: 571
    - pin: K33
      x: 2566
      y: 571
    - pin: K34
      x: 2633
      y: 571
    - pin: K35
      x: 2714
      y: 571
    - pin: K36
      x: 2791
      y: 571
    - pin: K37
      x: 2865
      y: 571
    - pin: K38
      x: 2940
      y: 571
    - pin: K39
      x: 3011
      y: 571
    - pin: K40
      x: 3086
      y: 571
    - pin: K41
      x: 3161
      y: 571
    - pin: K42
      x: 3235
      y: 571
    - pin: K43
      x: 3314
      y: 571
    - pin: K44
      x: 3386
      y: 571
    - pin: K45
      x: 3458
      y: 571
    - pin: K46
      x: 3530
      y: 571
    - pin: K47
      x: 3605
      y: 571
    - pin: K48
      x: 3681
      y: 571
    - pin: K49
      x: 3754
      y: 571
    - pin: K50
      x: 3827
      y: 571



    - pin: K51
      x: 2251
      y: 342
    - pin: K52
      x: 2340
      y: 342
    - pin: K53
      x: 2412
      y: 342
    - pin: K54
      x: 2492
      y: 342
    - pin: K55
      x: 2566
      y: 342
    - pin: K56
      x: 2633
      y: 342
    - pin: K57
      x: 2714
      y: 342
    - pin: K58
      x: 2791
      y: 342
    - pin: K59
      x: 2865
      y: 342
    - pin: K60
      x: 2940
      y: 342
    - pin: K61
      x: 3011
      y: 342
    - pin: K62
      x: 3086
      y: 342
    - pin: K63
      x: 3161
      y: 342
    - pin: K64
      x: 3235
      y: 342
    - pin: K65
      x: 3314
      y: 342
    - pin: K66
      x: 3386
      y: 342
    - pin: K67
      x: 3458
      y: 342
    - pin: K68
      x: 3530
      y: 342
    - pin: K69
      x: 3605
      y: 342
    - pin: K70
      x: 3681
      y: 342
    - pin: K71
      x: 3754
      y: 342
    - pin: K72
      x: 3827
      y: 342




    - pin: K73
      x: 2251
      y: 258
    - pin: K74
      x: 2340
      y: 258
    - pin: K75
      x: 2412
      y: 258
    - pin: K76
      x: 2492
      y: 258
    - pin: K77
      x: 2566
      y: 258
    - pin: K78
      x: 2633
      y: 258
    - pin: K79
      x: 2714
      y: 258
    - pin: K80
      x: 2791
      y: 258
    - pin: K81
      x: 2865
      y: 258
    - pin: K82
      x: 2940
      y: 258
    - pin: K83
      x: 3011
      y: 258
    - pin: K84
      x: 3086
      y: 258
    - pin: K85
      x: 3161
      y: 258
    - pin: K86
      x: 3235
      y: 258
    - pin: K87
      x: 3314
      y: 258
    - pin: K88
      x: 3386
      y: 258
    - pin: K89
      x: 3458
      y: 258
    - pin: K90
      x: 3530
      y: 258
    - pin: K91
      x: 3605
      y: 258
    - pin: K92
      x: 3681
      y: 258
    - pin: K93
      x: 3754
      y: 258
    - pin: K94
      x: 3827
      y: 258


    - pin: A1
      x: 301
      y: 660
    - pin: A2
      x: 410
      y: 660
    - pin: A3
      x: 520
      y: 660
    - pin: A4
      x: 623
      y: 660
    - pin: A5
      x: 724
      y: 660
    - pin: A6
      x: 815
      y: 660
    - pin: A7
      x: 897
      y: 660
    - pin: A8
      x: 967
      y: 660
    - pin: A9
      x: 1044
      y: 660
    - pin: A10
      x: 1118
      y: 660
    - pin: A11
      x: 1193
      y: 660
    - pin: A12
      x: 1270
      y: 660
    - pin: A13
      x: 1348
      y: 660
    - pin: A14
      x: 1414
      y: 660
    - pin: A15
      x: 1504
      y: 660




    - pin: A16
      x: 301
      y: 577
    - pin: A17
      x: 410
      y: 577
    - pin: A18
      x: 520
      y: 577
    - pin: A19
      x: 623
      y: 577
    - pin: A20
      x: 724
      y: 577
    - pin: A21
      x: 815
      y: 577
    - pin: A22
      x: 897
      y: 577
    - pin: A23
      x: 967
      y: 577
    - pin: A24
      x: 1044
      y: 577
    - pin: A25
      x: 1118
      y: 577
    - pin: A26
      x: 1193
      y: 577
    - pin: A27
      x: 1270
      y: 577
    - pin: A28
      x: 1348
      y: 577
    - pin: A29
      x: 1414
      y: 577
    - pin: A30
      x: 1504
      y: 577



    - pin: A31
      x: 301
      y: 353
    - pin: A32
      x: 410
      y: 353
    - pin: A33
      x: 520
      y: 353
    - pin: A34
      x: 623
      y: 353
    - pin: A35
      x: 724
      y: 353
    - pin: A36
      x: 815
      y: 353
    - pin: A37
      x: 897
      y: 353
    - pin: A38
      x: 967
      y: 353
    - pin: A39
      x: 1044
      y: 353
    - pin: A40
      x: 1118
      y: 353
    - pin: A41
      x: 1193
      y: 353
    - pin: A42
      x: 1270
      y: 353
    - pin: A43
      x: 1348
      y: 353
    - pin: A44
      x: 1414
      y: 353
    - pin: A45
      x: 1504
      y: 353



    - pin: A46
      x: 301
      y: 264
    - pin: A47
      x: 410
      y: 264
    - pin: A48
      x: 520
      y: 264
    - pin: A49
      x: 623
      y: 264
    - pin: A50
      x: 724
      y: 264
    - pin: A51
      x: 815
      y: 264
    - pin: A52
      x: 897
      y: 264
    - pin: A53
      x: 967
      y: 264
    - pin: A54
      x: 1044
      y: 264
    - pin: A55
      x: 1118
      y: 264
    - pin: A56
      x: 1193
      y: 264
    - pin: A57
      x: 1270
      y: 264
    - pin: A58
      x: 1348
      y: 264
    - pin: A59
      x: 1414
      y: 264
    - pin: A60
      x: 1504
      y: 264
