//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config\boards\hellen\vthpnp\connectors\main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_LS_1, // A1  - INJ 1
	Gpio::H144_LS_4, // A2  - INJ 4
	Gpio::H144_LS_2, // A2  - INJ 2
	Gpio::H144_OUT_PWM7, // A4  - VTS/HS1
	Gpio::H144_LS_3, // A5  - INJ 3
	Gpio::H144_IGN_6, // A6  - TACH
	Gpio::H144_OUT_IO11, // A7  - FP Rly
	Gpio::H144_OUT_PWM2, // A9  - IACV/PWM1
	Gpio::H144_OUT_PWM3, // A11 - EGR/PWM2
	Gpio::H144_OUT_IO8, // A12 - FAN Rly
	Gpio::H144_OUT_IO7, // A13 - MIL CTR
	Gpio::H144_OUT_IO4, // A15 - AC Rly
	Gpio::H144_OUT_IO13, // A16 - Alt CTR
	Gpio::H144_OUT_PWM5, // A17 - IAB/PWM3
	Gpio::H144_IGN_1, // A8  - IGN 1
	Gpio::H144_IGN_2, // A10 - IGN 2
	Gpio::H144_IGN_3, // A14 - IGN 3
	Gpio::H144_OUT_PWM6, // A18 - HS2
	Gpio::H144_IGN_5, // A21 - ICM CTR
	Gpio::H144_IGN_4, // A22 - IGN 4
// "A1  - INJ 1",
// "A2  - INJ 4",
// "A2  - INJ 2",
// "A4  - VTS/HS1",
// "A5  - INJ 3",
// "A6  - TACH",
// "A7  - FP Rly",
// "A9  - IACV/PWM1",
// "A11 - EGR/PWM2",
// "A12 - FAN Rly",
// "A13 - MIL CTR",
// "A15 - AC Rly",
// "A16 - Alt CTR",
// "A17 - IAB/PWM3",
// "A8  - IGN 1",
// "A10 - IGN 2",
// "A14 - IGN 3",
// "A18 - HS2",
// "A21 - ICM CTR",
// "A22 - IGN 4",
}
